In [15]:
import pandas as pd
import numpy as np

In [16]:
# load data
data = pd.read_csv("sfpuf2021_1_fall.csv").rename(columns = {"ADM_H_MEDSTA": "medicare_reason",
                                                             "DEM_AGE": "age",
                                                             "DEM_SEX": "sex",
                                                             "DEM_RACE": "race",
                                                             "HLT_OCPSYCHO": "mental_illness",
                                                             "ADM_DUAL_FLAG_YR": "medicaid",
                                                             "ADM_MA_FLAG_YR": "medicare_advantage",
                                                             "ADM_PARTD": "part_d",
                                                             "INS_D_PRIVNUM": "priv_1",
                                                             "INS_D_PVESI": "priv_2",
                                                             "INS_D_PVSELF": "priv_3",
                                                             "ACC_PAYPROB": "problem_paying_bills"})
data = data[["medicare_reason", "age", "sex", "race", "mental_illness", "medicaid", "medicare_advantage", "part_d", "priv_1", "priv_2", "priv_3", "problem_paying_bills"]]
data.head()

/var/folders/b3/rt6xbmt175g5bcvlg0sd0fqh0000gn/T/ipykernel_30586/3144253805.py:2: DtypeWarning: Columns (43,46,49,50,51,52,53,73,76,77,81,82,83,85,90,92,99,100,105,106,107,112,113,118,119,123,124,125,126,128,129,135,136,137,138,139,140,142,143,151,155,156,161,163,172,176,183,184,185,186,191,192,193,194,195,197,198,199,200,208,209,210,211,214,217,218,219,220,221,222,223,224,225,227,229) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("sfpuf2021_1_fall.csv").rename(columns = {"ADM_H_MEDSTA": "medicare_reason",

,medicare_reason,age,sex,race,mental_illness,medicaid,medicare_advantage,part_d,priv_1,priv_2,priv_3,problem_paying_bills
0,1,3,2,1,2,1,1,2,1,2,1,2
1,1,2,1,2,2,1,1,1,1,2,1,2
2,1,3,2,1,2,1,1,1,1,2,1,2
3,1,3,2,1,2,1,1,1,1,2,1,2
4,1,2,2,3,2,3,3,1,2,2,2,1

In [17]:
# clean relevant columns
data["medicare_reason"] = data["medicare_reason"].map({1: "Aged", 2: "Disabled", 3: "Unknown"})
data["age"] = data["age"].map({1: "<65", 2: "65-74", 3: "75+"})
data["sex"] = data["sex"].map({1: "Male", 2: "Female"})
data["race"] = data["race"].map({1: "Non-Hispanic White", 2: "Non-Hispanic Black", 3: "Hispanic", 4: "Other"})
data["mental_illness"] = data["mental_illness"].map({1: "Yes", "1": "Yes", 2: "No", "2": "No", "D": "Unknown", "R": "Unknown"}).fillna("Unknown")
data["medicaid"] = data["medicaid"].map({1: 0, 2: 1, 3: 1})
data["medicare_advantage"] = data["medicare_advantage"].map({1: 0, 2: 1, 3: 1})
data["part_d"] = data["part_d"].map({1: 1, 2: 0})
data["priv_1"] = data["priv_1"].map({1: 1, 2: 0})
data["priv_2"] = data["priv_2"].map({1: 1, 2: 0})
data["priv_3"] = data["priv_3"].map({1: 1, 2: 0})
data["private_insurance"] = data[["priv_1", "priv_2", "priv_3"]].sum(axis = 1)
data["private_insurance"] = np.where(data["private_insurance"] > 1, 1, 0)
data = data.drop(columns = ["priv_1", "priv_2", "priv_3"])
data["problem_paying_bills"] = data["problem_paying_bills"].map({1: 1, "1": 1, 2: 0, "2": 0}).astype("Int64")
data.head()

,medicare_reason,age,sex,race,mental_illness,medicaid,medicare_advantage,part_d,problem_paying_bills,private_insurance
0,Aged,75+,Female,Non-Hispanic White,No,0,0,0,0,1
1,Aged,65-74,Male,Non-Hispanic Black,No,0,0,1,0,1
2,Aged,75+,Female,Non-Hispanic White,No,0,0,1,0,1
3,Aged,75+,Female,Non-Hispanic White,No,0,0,1,0,1
4,Aged,65-74,Female,Hispanic,No,1,1,1,1,0

In [18]:
# export to csv
data.to_csv("rachel_data_cleaned.csv")